### PR TITLE
Bump Serilog version dependency to support Unity and .netstandard 2.0+

### PR DESCRIPTION
**Pull request by bdovaz**
Same problem as this

https://github.com/serilog/serilog-extensions-logging/pull/188

### CODE REVIEW

**Comment by bdovaz** [comment]
@nblumhardt Yes, please, if you don't mind changing it yourself because I don't have any experience with Nuget's publishing flow.

**Comment by Numpsy** [comment]
refs #71 :-)

**Comment by bdovaz** [comment]
@nblumhardt Failed due to nuget's API key saying it is expired or invalid.

https://ci.appveyor.com/project/serilog/serilog-sinks-async

**Comment by nblumhardt** [comment]
Should be fixed now, thanks 👍

**Pull request merged**
