### PR TITLE
Make file version match assembly version

### LINKED ISSUE #37: File Version in 1.3.0 Release Incorrect
Serilog.Sinks.Async.dll 1.1.0 has a FileVersion of 1.1.0.  Recently upgrading to 1.3.0 and the Serilog.Sinks.Async.dll has a FileVersion of 1.0.0.  I would expect the FileVersion to be 1.3.0 or at least greater than one of the previous versions. The FileVersion instead has gone backwards.  This causes issues with some installer technologies.

### PR DESCRIPTION
**Pull request by mattpwhite**
Fixes #37 

I just edited the csproj.  It looks like this is what the Package panel in VS would do as well.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks Matt! I think this is the best way forwards if we've regressed the version 👍 

Unfortunately the other Serilog sinks get around this easily by having a static (usually 1.0) assembly version. We should nudge this package back in that direction in the long run, i.e. at its 2.0.

**Comment by mattpwhite** [comment]
Sure, whatever makes sense, I was just looking for a quick fix because this was breaking upgrades via msi for one of my apps.  Any idea when this might be pushed to NuGet?  If it will be a while, I’ll work around the issue, otherwise I’d just pick up the updated package.

And thanks for merging so quickly.

**Comment by nblumhardt** [comment]
This changeset has been published as a -dev version; we'll push it through to master at some point, it'd be great if you can check that the dev version addresses the problem for you, some validation would help with getting this through the release process. Cheers!

**Comment by mattpwhite** [comment]
> This changeset has been published as a -dev version;

Good enough for me.  I can confirm that this fixes the update issues for my installer.  Thanks again.

**Pull request merged**
